@baseUrl=http://192.168.1.5:3000

### --------------------------------------------
### Encrypt helper
# -------------- Pre Script -------------------------

POST {{baseUrl}}/api/cpps/encrypt

{
    "token": "MG/11xx",
}

# -------------- Post Script -------------------------


### Decrypt helper
POST {{baseUrl}}/api/cpps/decrypt

{
  "payload": "gAAAAABquAAG_2OqVN2LOOzged7AFx0YjYwD5MXojnhRL2gweNtZooHNpDAD7EEo2gTlf3VwFhCpquSZ6wqffrANaSnlVa182NTRX_wQISvK45WKyN3GaxSK8C0z_vocR_-mlH96_2CAClcfhmEG6Rf-BloC7hM3HWRZukYLEIPwVvHlRAKvx7deJ1xdKX8t6ufbA6ZzDyIr7fudalQoNkCJ2uyF8ZIRh8CpWnrymLwLh0R4mlNxWg06XSi70LfCDYfH2Mc6jOTGpPtydSWnt7LSsicCwqXjc1C1fdXmfx83JXA1lNCbxDfeM7DrRhEPjIb_49RIx5TvW7cuSkUL1P8AF6ImRA_KYMny0LZogeiLw2f26fsk2m0="
}


### format-password helper
POST {{baseUrl}}/api/cpps/format-password

{
  "password": "{{PASSWORD}}"
}

### echo
POST http://localhost:3000/api/echo/123

{
  "url":"/get_ppo_status",
  "status_code":200,
  "data":{ 
     "success":true,
     "data":"gAAAAABqtNTrfAsSHkMZB0WPWLKUjxytsrLwOPo2kjPJ6mGp52Iw4XB7kRVwh85mWJlFLTJGDsvDBcwP4CjrzjpXZVjoTShiVZbtKioWjXK2vMqW_uuvkUyk6fKhUR528Cr5rbIoXAWNftxcrku5VgGxMNVl1hGnA4sxQGXGwzqJsXFTntSmEivH_Ky6xD6_L6CC5hRctQcG"
  }
}

### echo
< {%
   request.variables.set('RAW_BODY', JSON.stringify({
     url:"/login",
     status_code:200, 
     data:{ 
        "success":true,
        "data": "gAAAAABqt2kpwI15lsEpgBTbzTu_dPsEwXstsZzhYF-z5kvmBSmgNzp3E8_tGzhtpEKC40Dz1vnECFi2hLjrsNFwmjJ3KeIvKdyFVWbanL3q3a2N8VZKSkI="
     }
   }));
%}

POST {{baseUrl}}/api/echo

{ 
  "url":"/logout",
  "status_code":200,
  "data": { 
    "message":"success"
  }
}

###
GET http://192.168.1.5:3000/api/echo
