### --------------------------------------------
### Encrypt helper
# -------------- Pre Script -------------------------
# < {%
#    require('./scripts/enc-req.http.js');
# %}

POST http://localhost:3000/api/cpps/PensionersApp/v1/encrypt

{
  "data": "gAAAAABqs3m88JDQYzKlvOCS7UZRcjGp4nFctMqosVSL7e2maFfvUaetCR54PbG58Qmpl_Nm9Wm9_9X6emrw8Hhs4AmQ-2nayw=="
}

# -------------- Post Script -------------------------
> {%
  require('./scripts/dec-res.http.js');
%}


### --------------------------------------------
### Decrypt helper

< {%
   require('./scripts/enc-req.http.js');
%}

POST http://localhost:3000/api/cpps/PensionersApp/v1/decrypt

{
  "payload": "123"
}

> {%
  require('./scripts/dec-res.http.js');
%}
### --------------------------------------------

### --------------------------------------------
### format-password helper
POST http://localhost:3000/api/cpps/PensionersApp/v1/format-password

{
  "password": "{{PASSWORD}}"
}

### --------------------------------------------
