### --------------------------------------------
### Encrypt helper
# -------------- Pre Script -------------------------
< {%
   require('./scripts/enc-req.http.js');
%}

POST http://localhost:3000/api/cpps/PensionersApp/v1/encrypt

{
  "data": "123"
}

# -------------- Post Script -------------------------
> {%
  require('./scripts/dec-res.http.js');
%}


### --------------------------------------------
### Decrypt helper

< {%
   require('./scripts/enc-req.http.js');
%}

POST http://localhost:3000/api/cpps/PensionersApp/v1/decrypt

{
  "payload": "123"
}

> {%
  require('./scripts/dec-res.http.js');
%}
### --------------------------------------------

### --------------------------------------------
### format-password helper
POST http://localhost:3000/api/cpps/PensionersApp/v1/format-password

{
  "password": "{{PASSWORD}}"
}

### --------------------------------------------
