# --------------------------------------------
# Pensioner v2
# --------------------------------------------

# # Pre-script
# < {% 
#    require("./scripts/enc-req.http.js");
# % }

###  login
POST {{BASE_URL}}/login

{
  "payload":"{{LOGIN_PAYLOAD}}"
}

# Post-script

> {% 
   require("./scripts/dec-res.http.js");
%}

# ----------------------------
# Response
# ----------------------------
# {
#   "data": {
#     "token": "[Redacted]"
#   },
#   "message": "Authenticate",
#   "success": true
# }
# ----------------------------

###  pension statement
POST {{BASE_URL}}/paymentslip

# ----------------------------
# Payload
# ----------------------------
# { 
#   "pp_no":"[Redacted]"
# }
# ----------------------------

{
  "payload":"{{PAYMENT_SLIP_PAYLOAD}}"
}
# ----------------------------
# Response
# ----------------------------
#   {
#   "pdf": "string",
#   "pension": [
#     {
#       "age_bonus": "string",
#       "arr_gross": "string",
#       "bp": "string",
#       "comm_gross": "string",
#       "da": "string",
#       "date_frm": "string",
#       "date_to": "string",
#       "ddo_bill_date": "string",
#       "ddo_bill_date_format": "string",
#       "deduction": "string",
#       "dp": "string",
#       "dra": "string",
#       "fin_year": "string",
#       "gra_gross": "string",
#       "ma": "string",
#       "net_amt": "string",
#       "no_of_months": "string",
#       "oth": "string",
#       "pen_gross": "string",
#       "ppo_id": "string",
#       "tran_date": "string",
#       "tran_id": "string",
#       "wa": "string"
#     }
#   ],
#   "success": true
# }
# ----------------------------


### pension logout
POST {{BASE_URL}}/logout

{
 "token":"{{ACCESS_TOKEN}}"
}

# ----------------------------
# Response
# ----------------------------
# {
#   "message": "success"
#   "status": true,
# }
# ----------------------------

### get-ppo-status 
POST {{BASE_URL}}/get_ppo_status

# ----------------------------
# Payload
# ----------------------------
# { 
#   "pp_no":"[Redacted]"
# }
# ----------------------------

{
 "payload":"{{PAYMENT_SLIP_PAYLOAD}}"
}

# ----------------------------
# Response
# ----------------------------
# {
#   "payload": {
#     "ppo_no": "string",
#     "pname": "string",
#     "dob": "string",
#     "bank_accno": "string"
#   }
# }
# "success": true | false
# }
# ----------------------------

### get-user 
POST {{BASE_URL}}/user

# ----------------------------
# Payload
# ----------------------------
# {}
# ----------------------------

{}

> {% 
   require("./scripts/decrypt-response.http.js");
%}

# ----------------------------
# Response
# ----------------------------
# {
# "data": {
#   "app_date": "string",
#   "app_exp": "string",
#   "bank_accno": "string",
#   "dob": "string",
#   "gender": "string",
#   "member_id": "string",
#   "mtype": "string",
#   "pclass": "string",
#   "pclass_cd": "string",
#   "photo": "string",
#   "pname": "string",
#   "ppo_id": "string",
#   "ppo_no": "string",
#   "ptype_cd": "string",
#   "rela": "string",
#   "trea_code": "string",
#   "treasury_name": "string"
#  },
#  "message": "string",
#  "status": "boolean"
# }
# ----------------------------

### facial-registration
POST {{BASE_URL}}/facial_registration

# ----------------------------
# Payload
# ----------------------------
# { 
#   "ppo_no": "[Redacted]",
#   "dob": "[Redacted]",
#   "bank_accno": "[Redacted]",
#   "password":"[Redacted]",
#   "image":"{{EXPO_PUBLIC_TEST_IMAGE}}"
# }
# ----------------------------

{
  "payload":"{{FACIAL_REG_PAYLOAD}}"
}

# ----------------------------
# Response
# ----------------------------
# {
#  "data": {},
#  "message": "string",
#  "status": "boolean"
# }
# ----------------------------

### submit-dlc
POST {{BASE_URL}}/dlc

# ----------------------------
# Payload
# ----------------------------
# { }
# ----------------------------

{
  "payload":"{{FACIAL_REG_PAYLOAD}}"
}

# ----------------------------
# Response
# ----------------------------
# {
#  "data": { },
#  "message": "string",
#  "status": "boolean"
# }
# ----------------------------

### dlc-status
POST {{BASE_URL}}/dlc_status

# ----------------------------
# Payload
# ----------------------------
# { }
# ----------------------------

{
  "payload":"{{FACIAL_REG_PAYLOAD}}"
}

# ----------------------------
# Response
# ----------------------------
# {
#  "data": { },
#  "message": "string",
#  "status": "boolean"
# }
# ----------------------------
