# --------------------------------------------
# Pensioner v2
# --------------------------------------------

###  login
POST {{BASE_URL}}/login
# ----------------------------
# Payload
# ----------------------------
# { 
#   "username":"[Redacted]",
#   "password":"[Redacted]"
# }
# ----------------------------


{
  "payload":"{{LOGIN_PAYLOAD}}"
}

# ----------------------------
# Response
# ----------------------------
# {
#   "data": {
#     "token": "[Redacted]"
#   },
#   "message": "Authenticate",
#   "success": true
# }
# ----------------------------

###  pension statement
POST {{BASE_URL}}/paymentslip

# ----------------------------
# Payload
# ----------------------------
# { 
#   "pp_no":"[Redacted]"
# }
# ----------------------------

{
  "payload":"{{PAYMENT_SLIP_PAYLOAD}}"
}
# ----------------------------
# Response
# ----------------------------
#   {
#   "pdf": "string",
#   "pension": [
#     {
#       "age_bonus": "string",
#       "arr_gross": "string",
#       "bp": "string",
#       "comm_gross": "string",
#       "da": "string",
#       "date_frm": "string",
#       "date_to": "string",
#       "ddo_bill_date": "string",
#       "ddo_bill_date_format": "string",
#       "deduction": "string",
#       "dp": "string",
#       "dra": "string",
#       "fin_year": "string",
#       "gra_gross": "string",
#       "ma": "string",
#       "net_amt": "string",
#       "no_of_months": "string",
#       "oth": "string",
#       "pen_gross": "string",
#       "ppo_id": "string",
#       "tran_date": "string",
#       "tran_id": "string",
#       "wa": "string"
#     }
#   ],
#   "success": true
# }
# ----------------------------


### pension logout
POST {{BASE_URL}}/logout

{
 "token":"{{ACCESS_TOKEN}}"
}

# ----------------------------
# Response
# ----------------------------
# {
#   "message": "success"
#   "status": true,
# }
# ----------------------------

### get-ppo-status 
POST {{BASE_URL}}/get_ppo_status
Content-Type: application/json

# ----------------------------
# Payload
# ----------------------------
# { 
#   "pp_no":"[Redacted]"
# }
# ----------------------------

{
 "payload":"{{PAYMENT_SLIP_PAYLOAD}}"
}

# ----------------------------
# Response
# ----------------------------
# {
#   "payload": {
#     "ppo_no": "string",
#     "pname": "string",
#     "dob": "string",
#     "bank_accno": "string"
#   }
# }
# "success": true | false
# }
# ----------------------------
